# Generated by Django 4.0 on 2021-12-24 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_vaccination_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccinationCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.pet')),
                ('vaccination', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.vaccination')),
            ],
        ),
    ]
