# Generated by Django 4.0 on 2021-12-25 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_vaccinationcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='vet',
            name='email',
            field=models.CharField(default='nmutlu17@ku.edu.tr', max_length=100),
        ),
        migrations.AddField(
            model_name='vet',
            name='password',
            field=models.CharField(default='test', max_length=100),
        ),
    ]
