# Generated by Django 4.0 on 2021-12-25 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_claim'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='pet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.pet'),
        ),
    ]
