# Generated by Django 4.0 on 2021-12-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_claim_pet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccinationcard',
            name='patient',
        ),
        migrations.AddField(
            model_name='pet',
            name='gender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='insurance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='vaccineStatus',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
