# Generated by Django 4.0 on 2021-12-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_remove_vaccinationcard_patient_pet_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill', models.FileField(blank=True, null=True, upload_to='files')),
                ('animalType', models.CharField(max_length=100)),
            ],
        ),
    ]
