# Generated by Django 4.0 on 2021-12-25 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_rename_animaltype_case_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='vet',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.vet'),
        ),
    ]
