# Generated by Django 4.0 on 2021-12-26 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_remove_askidasigorta_usedforvet_remove_case_vet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='askidasigorta',
            name='usedForVet',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.vet'),
        ),
        migrations.AddField(
            model_name='case',
            name='vet',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.vet'),
        ),
        migrations.AddField(
            model_name='claim',
            name='veterinary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.vet'),
        ),
        migrations.AddField(
            model_name='comments',
            name='vet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.vet'),
        ),
    ]
